import {
    defineConfig,
    presetWebFonts,
    presetIcons,
    presetTypography,
    transformerVariantGroup,
    transformerDirectives,
} from 'unocss'
import presetWind4 from '@unocss/preset-wind4'

export default defineConfig({
    safelist: [
        // Dynamic avatar classes used in JavaScript
        'w-10',
        'h-10',
        'w-32',
        'h-32',
        'w-80px',
        'h-80px',
        'w-20',
        'h-20',
        'left-50%',
        'transform',
        '-translate-x-50%',
        'text-24px',
        '-top-10',
        'absolute',
        'shadow-lg',
        'overflow-visible',
        'text-sm',
        'text-4xl',
        'text-2xl',
        'rounded-full',
        'bg-brand-blue',
        'bg-brand-blue-dark',
        'bg-brand-green',
        'bg-brand-orange',
        'bg-brand-orange-dark',
        'text-white',
        'flex',
        'items-center',
        'justify-center',
        'font-bold',
        'uppercase',
        'object-cover',
        'bg-gray-200',
        'mx-auto',
        'mb-5',
        // Button state classes
        'bg-gray-500',
        'cursor-not-allowed',
        'hover:bg-green-700',
        'hover:bg-brand-orange-dark',
        'hover:scale-105',
        'active:scale-95',
        // Floating button classes
        'fixed',
        'w-16',
        'h-16',
        'bottom-6',
        'right-6',
        'shadow-xl',
        'shadow-2xl',
        'hover:scale-110',
        'bg-gray-400',
        'hover:shadow-2xl',
        'z-50',
        'top-5',
        'left-5',
        // Body width classes
        'w-full',
        'max-w-full',
        // Modern design classes
        'rounded-xl',
        'shadow-sm',
        'hover:shadow-md',
        'border-gray-100',
        'hover:border-gray-200',
        'mb-4',
        'p-6',
        'duration-200',
        'scrollbar-modern',
        'gap-2',
        // Clear all button classes
        'bg-red-600',
        'hover:bg-red-700',
        'cursor-pointer',
        'cursor-not-allowed',
        'disabled:bg-gray-400',
        'disabled:cursor-not-allowed',
        // UnoCSS Icons
        'i-mdi-github',
        'i-heroicons-chat-bubble-left-ellipsis',
        'i-heroicons-chevron-down',
        'i-heroicons-star',
        'i-heroicons-heart',
        'i-heroicons-cog-6-tooth',
        'i-heroicons-x-mark',
        'i-heroicons-check-circle',
        'i-heroicons-sun',
        'i-heroicons-moon',
        'i-heroicons-computer-desktop',
        'i-heroicons-trash',
        'i-heroicons-arrow-down-tray',
        'i-heroicons-exclamation-triangle',
        'i-heroicons-arrow-left',
        // Card layout classes
        'flex-col',
        'min-h-[320px]',
        'flex-grow',
        'mt-auto',
        'pt-20',
        'pb-8',
        'px-8',
        'gap-x-8',
        'gap-y-16',
        'mt-20',
        // Theme switch classes
        'bg-white',
        'text-slate-900',
        'shadow-sm',
        'text-slate-600',
        'hover:text-slate-900',
        // Default bot indicator classes
        'border-2',
        'border-brand-blue',
        'bg-blue-50',
        'absolute',
        'top-2',
        'right-2',
        'rounded-full',
        'font-semibold',
        'hover:bg-brand-blue-dark',
        // Carousel navigation classes
        'i-heroicons-chevron-left',
        'i-heroicons-chevron-right',
        // Carousel dot classes
        'w-2',
        'h-2',
        'w-6',
        'rounded',
        'bg-gray-300',
        'bg-gray-400',
        'dark:bg-gray-600',
        'dark:bg-gray-500',
        'hover:bg-gray-400',
        'dark:hover:bg-gray-500',
        'bg-brand-blue',
        'dark:bg-blue-500',
        'transition-all',
        'duration-300',
        'focus:outline-none',
        'focus:ring-2',
        'focus:ring-brand-blue',
        'focus:ring-offset-2',
        'dark:focus:ring-blue-500',
    ],
    presets: [
        presetWind4({
            preflights: {
                reset: true,
                theme: 'on-demand',
            },
        }),
        presetIcons({
            scale: 1.2,
            cdn: 'https://esm.sh/',
        }),
        presetTypography(),
        presetWebFonts({
            provider: 'google',
            fonts: {
                sans: 'Inter:400,500,600,700',
                mono: 'Fira Code',
            },
            inlineImports: false,
            timeout: 5000,
        }),
    ],
    transformers: [transformerVariantGroup(), transformerDirectives()],
    theme: {
        colors: {
            primary: {
                DEFAULT: '#3b82f6',
                50: '#eff6ff',
                100: '#dbeafe',
                200: '#bfdbfe',
                300: '#93c5fd',
                400: '#60a5fa',
                500: '#3b82f6',
                600: '#2563eb',
                700: '#1d4ed8',
                800: '#1e40af',
                900: '#1e3a8a',
                950: '#172554',
            },
            'brand-blue': '#2563eb',
            'brand-blue-dark': '#1d4ed8',
            'brand-green': '#059669',
            'brand-orange': '#f59e0b',
            'brand-orange-dark': '#d97706',
            'github-dark': '#24292e',
            'github-darker': '#1b1f23',
            'gray-light': '#f5f5f5',
        },
    },
    shortcuts: {
        btn: 'px-4 py-2 rounded-lg bg-primary text-white hover:bg-primary-600 transition-colors duration-200',
        'btn-outline':
            'px-4 py-2 rounded-lg border border-primary text-primary hover:bg-primary hover:text-white transition-colors duration-200',
        card: 'p-6 rounded-xl bg-white shadow-lg',
        input: 'px-4 py-2 rounded-lg border border-gray-300 focus:border-primary focus:outline-none transition-colors',
    },
    rules: [
        [
            'custom-scrollbar',
            {
                'scrollbar-width': 'thin',
                'scrollbar-color': '#cbd5e1 #f1f5f9',
            },
        ],
    ],
})
